### ISSUE TITLE
Store the database credentials in a .ini file

### ISSUE THREAD

**Issue by ghost** [Sreyas-Sreelal/SS-Gang-System-SQLITE#11]
The scripter has to recompile the script every time they change the credentials for their database. To recompile the script, they also need all the includes. While a scripter is expected to have all these, it's not guaranteed.

The first possible solution that I can think of is the use of a `.ini` file that stores all this data. Any better ideas?

**Comment by Sreyas-Sreelal** [comment]
Hmm i ain't get any better idea so yeah we can store them in a file.

**Comment by ghost** [comment]
Yes i suggest to use a file for store the configurations files ( json file ) using a_json from [LVP ](https://github.com/LVPlayground/json-plugin/blob/master/server/a_json.pwn)

about the plugin use [this](https://github.com/LVPlayground/server-staging/blob/master/server/plugins/json-plugin.dll)

Json_prase fonction is the better way for this

**Comment by Sreyas-Sreelal** [comment]
Ok here is the  idea  that came to my mind now.

What about creating a console app to create ini file that will be processed by script? So that we can hash the password using the app. I can create one in c++.

**Comment by ghost** [comment]
It's worth a try. Will it work within samp's console?

**Comment by Sreyas-Sreelal** [comment]
Hmm i dont think so.

**Comment by ghost** [comment]
what about batch file :/ is easy

**Comment by Sreyas-Sreelal** [comment]
Can hashing algorithms can be applied in batch files? Idk

**Comment by Sreyas-Sreelal** [comment]
Ok i have created it let me know your opinion about it.

**Comment by ghost** [comment]
Nice one but how that will help with the configurations informations ? and how it will be merged to gamemode ?

**Comment by Sreyas-Sreelal** [comment]
it just creates configuration files in .ini format with sha256 hashing algorithm.

**Comment by ghost** [comment]
so how the server will read it as sha256 hashing algorithm ?

**Comment by Sreyas-Sreelal** [comment]
That was a good question we didn't think that mysql_connect takes the arguement in plane password so checking the hashed one with plane one will give us error and there is no way to dehash sha256. Hmm let me investigate on that. Do you guys know some remedy in this case?

**Comment by ghost** [comment]
What about udb hash on C++ ?? it's can be unhashed for using i think

**Comment by Sreyas-Sreelal** [comment]
Then there is  point in hashing. I have opened an issue in mysql plugin repo. Hope maddinator finds an answer.

**Comment by Sreyas-Sreelal** [comment]
Ok we cant do it https://github.com/pBlueG/SA-MP-MySQL/issues/134. But im not going to delete this let me check if it can be implemented.

**Comment by ghost** [comment]
as MySQL Plugin Collaborator reponse https://github.com/pBlueG/SA-MP-MySQL/issues/134
they can't implement this function so we need another way to hash and unhash this :/

**Comment by Sreyas-Sreelal** [comment]
I dont get much better idea.

**Comment by ghost** [comment]
why not using udb hash ? 

C++ APP To hash ==> Server can unhash the udb ==> Then Server Ready :/ ?

**Comment by Sreyas-Sreelal** [comment]
As i told you if the hashes can dehashed easily then there is no point in adding hashing the hackers who may hack the host can get this details in file  and dehash them.Therefore adding plain text and weak hashes make no difference.

**Comment by ghost** [comment]
hmm now im very confused :/
