### ISSUE TITLE
Some AMX Backtrace

### ISSUE THREAD

**Issue by ghost** [Sreyas-Sreelal/SS-Gang-System-SQLITE#21]
I Noticed Some Errors in the log while loading The FS 
vv

![capture](https://cloud.githubusercontent.com/assets/19735645/20563120/00718662-b17f-11e6-96a6-294244347ca7.PNG)

any idea ._. ?

and some others errors when player join but stoped after he leave 

http://pastebin.com/gZKaZKuq

**Comment by Konstantinos-Sk** [comment]
It is supposed to be a filterscript, crashdetect reporting _OnGameModeInit_ and _main()_ functions indicates that is not? Compiling with [debug info](https://github.com/Zeex/samp-plugin-crashdetect/wiki/Compiling-scripts-with-debug-info) would give more details.

Plus that is another reason I wanted to get rid of YSI library and have dynamic areas (by streamer plugin) and foreach as standalone.

**Comment by ghost** [comment]
what about the second one ?

**Comment by ghost** [comment]
Im using Bare script i don't think there any problem on it + fs when load get merged with the gamemode 

so OnFilterScripinit get merged with OnGamemodeinit

**Comment by Konstantinos-Sk** [comment]
What do you exactly mean by "get merged with the gamemode"? Please, post a log with debug info so I can actually understand what exactly happens and the run time error 6 is definitely due to YSI.

By the way, what branch are you using?

**Comment by ghost** [comment]
Im using MySQL Branch

http://pastebin.com/FC2SdbT3

**Comment by Konstantinos-Sk** [comment]
An old version of YSI and still not debug info. You might want to try the [streamer implementation](https://github.com/Sreyas-Sreelal/SS-Gang-System-SQLITE/tree/Streamer-Implemetntation) which doesn't use _y_areas_ and/or _y_iterate_.
