### ISSUE TITLE
Unnecessary breaklines

### ISSUE THREAD

**Issue by AmirSavand** [Sreyas-Sreelal/SS-Gang-System-SQLITE#22]
I mean are you serious?

**Comment by Sreyas-Sreelal** [comment]
Coding styles are different for different person please dont  open issues on such a thing(other than for an unreadable code ).If you find any critical bug or suggestion to optmise the script open an issue or do a pull request.

**Comment by AmirSavand** [comment]
At least give me a link of the code style documentation you are following,
Cuz I've never seen something like that.

**Comment by AmirSavand** [comment]
Also, I have an old Gang system, if you want I'll send you the .pwn.
Gang zones are saved in a json file and each gangzone is a location,

like: Our territory at Glen Park is under attack.

**Comment by Sreyas-Sreelal** [comment]
I did that coding style in past because the pawn editor provided a bad environment to write scripting and it was irritating to thats why the code looks like that.The coding style is not a name specific one though but you can find this type of coding styles in old dos scripting.
