### ISSUE TITLE
Requesting /backup ability for gangmembers

### ISSUE THREAD

**Issue by AmirSavand** [Sreyas-Sreelal/SS-Gang-System-SQLITE#23]
I hope this one is valid :P
Anyway I'm going to make a pull request.

**Comment by amirm3hdi** [comment]
I hope this one is valid :P 
Anyway I'm going to make a pull request.

**Comment by AmirSavand** [comment]
@Konstantinos-Sk The branch for pull request is ready, but I can't push the branch,
Need access rights.
```
$ git push origin backup-command 
ERROR: Permission to Sreyas-Sreelal/SS-Gang-System-SQLITE.git denied to amirm3hdi.
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
```

**Comment by Konstantinos-Sk** [comment]
Fork it, push necessary commits and pull request.

**Comment by AmirSavand** [comment]
@Konstantinos-Sk Done, I'm not used to contributing.
I have an AWESOME gang system, I just wanned to give it a feature of mine too.
