### ISSUE TITLE
Convert to INI

### ISSUE THREAD

**Issue by ghost** [Sreyas-Sreelal/SS-Gang-System-SQLITE#5]
Hello SS !

i need this script for merge it to San Andreas Playground Gamemode
but i don't think SQLite is good so i need it to be on INI or Mysql

but i don't have time (School DAMN !!) and i'm not good on Converting From SQLite to something

Please if u have a free time do u can convert it for me (in a Tree on Github ofc ) ? :) 

Thanks 
Yaa (Yassine)

**Comment by ghost** [comment]
Converting it to INI is a terrible idea. Moreover, the reason it is written with SQLite is because it doesn't need a ton of predefined login credentials for a MySQL server. It's pretty much made so that any server can plug it in and play with it ("plug and play") and MySQL takes away that aspect.

Nonetheless, I don't mind converting it to MySQL (+R40) in my spare time.

**Comment by ghost** [comment]
i means a custom script for me in another branch on this repos 
i need it on INI or MySQL R40 one of them 
and i like this script :)

**Comment by ghost** [comment]
Creating a specialized version of the script isn't what this whole thing is for. I don't mind converting it to MySQL (if Sreyas allows me to have a branch for it), but that's all I'll do. Editing it to your likings is completely up to you.

**Comment by Sreyas-Sreelal** [comment]
As Andy said converting this gang system to a file system is not a good idea and there is no need of MySQL like elaborated DB system for this script. 

@AndySedeyn You can have a branch for that :).
