### ISSUE TITLE
Code corrigenda

### ISSUE THREAD

**Issue by ghost** [Sreyas-Sreelal/SS-Gang-System-SQLITE#6]
This is a list of mistakes, questionable or improvable code that I came across while updating the filterscript to MySQL:

### PAWN
~1. Gang data and user data are put into the same enum. While not wrong and absolutely fine, it's ambiguous and may cause confusion (this was especially the case for me) (see further references to this).~

2. https://goo.gl/KDQhbF : `_Zone` is a non-descriptive name.

~3. https://goo.gl/6JEqW2 : There's a for-loop and I can't figure out a logical reason for it. It has no body and does exactly what the do-while loop does.~

~4. https://goo.gl/zVHhqe (till line 305): zMinX, zMinY, zMaxX and zMaxY are defined as floats, but loaded in as integers.~

5. https://goo.gl/dnyDzG : These values can be stored in a database. It brings more flexibility to the script as well as more predefined choices (what if the server wants them to be `true` upon starting the filterscript?).

~6. https://goo.gl/fBMw0E : You're addressing ZInfo of which the first dimension is limited to `MAX_GZONES`, but you're using `SS_Player` to iterate through it. Shouldn't that be `Zones`?~

~7. (No specific line): You are oversizing quite a few string variables.~

~8. (No specific line): `gangleader` can only assume two values: `0` or `1`. It would be more convenient if you declare it as a boolean variable and a tiny integer in the database (this is debatable since PAWN is a typeless language).~

~9. https://goo.gl/Yao89G: You are retrieving the player's name in OnPlayerText while you have it stored in a global variable.~

~10. (No specific line): You are creating new string variable under each flow control statement while it would be better to move the declaration to outside the statement and reuse it throughout the function. The naming would be a bit ambiguous, but it's a good habit (and possibly even more efficient).~

### SQL
~1. The overall database structure seems odd to me. (PAWN N°1) **(*)**~
~2. The database lacks relations where they are useful.~
    ~1. An example of such is the `members` table. It has a column `GangName`, but I don't see the use for that. You can retrieve the gang's name, of which the player is a member, by running an extra `SELECT` query or reversing the SELECT query via a relationship (FK).~

~**(*)** A few alternatives to handle gamemode tables better:~
~- Create an include that handles logging in and registering (a callback OnPlayerLogin/OnPlayerRegister?)~
~- Assume the server doesn't have a players table and force data into it when the player spawns~
~- Lay restrictions to the server that it is loaded on:~
     ~- The server must restart after loading the filterscript~
     ~- The server must execute a few predefined commands to get it all working correctly~

~In case that you don't want to assume that the gamemode doesn't have a players table, then the best alternative would be to force the scripter to adjust a few defines in the filterscript.~

---

I based all these points on assumptions. I assumed something while it might mean something else, so please, don't take this as absolute criticism. The conversion isn't completed yet by the time I submit this issue, so it doesn't include all the code that I thought needed a more detailed explanation. Notice that most of the points brought up can be found when scrolling through the first 200 lines.

Let us have an open discussion about what your intentions were/are at certain parts. They may not be as clear to me by just reading the code :)

**Comment by ghost** [comment]
about the point number 4 i don't think u lost some effort on it :/

anyway do u can post the code of the fs ? on The MySQL Branch let's fix it and let's Cooperate to fix it :D

 https://github.com/Sreyas-Sreelal/SS-Gang-System-SQLITE/tree/MySQL

**Comment by ghost** [comment]
I'm not going to commit every single line that I change. I'm quickly converting it in a whole and I'll commit it then ;)

As for point 4, I don't understand what you said.

**Comment by ghost** [comment]
just use Github Desktop version is best way to fast commit :D

**Comment by Sreyas-Sreelal** [comment]
First of all i wont consider pointing out mistakes (only friends or people care about our projects would do that rest will just ignore it),as criticism and not telling the mistakes is evil thing.I wouldn't put the project in github if so. Pointing out mistakes is necessary for any projects or scripts to improve even if its small or big.As different people views the code from different angles and all angles needed to be fixed.Thats why github made for :).

1.Some of the gang data and user data is put in same enum with an aim to connect or to do a equi-join with them.Its use mainly reflects in gang war.
2._Zone stores the returned value GangZonecreate i couldn't get any better name for it thats why i put it _Zone.
3.I recently done some optimisations to loops for fetching data (changed some for loop to do while) and i forgot change the older loop while putting new -_-.Thanks for pointing it out :).(Now fixed)
4.Changed them to  db_get_field_assoc_float.(Fixed)
5.While making the beta version i asked few people for suggestion about zone system and my first intention was also to store locked state in db but many of the people ,in a stunt server,suggested not to do that.(a server called ARRIBBA )  
6.Changed the mismatch iterator thanks :).(Fixed)

SQL:
As i told above gang name was added in both table with an aim of doing an equi-join in future.

Thanks for last suggestions i would try to implement as i get time since these days im sooo busyy  :(

**Comment by ghost** [comment]
Awesome, dude! I will, of course, help you with that 😃 . I will also update this issue _if_ I bump into more.

**Comment by Sreyas-Sreelal** [comment]
Thanks a lot Andy :)

**Comment by ghost** [comment]
Me too i will try to help :)

**Comment by Sreyas-Sreelal** [comment]
Ok i fixed some string sizes  and fixed a bug that we didn't noticed earlier.The tag command was built to replace all the name of gang members with leader's name it had to be in the loop and give a prefix to all members.
And Optmisation @ onplayer text is also done.Thanks :)

**Comment by ghost** [comment]
I don't want to make a separate issue for this, but it's too important to edit it in the main issue as it's slowing down the converting. The problem lies within the capture command:

``` PAWN
CMD:capture(playerid)
{

    if(GInfo[playerid][gangmember] == 0) return SendClientMessage(playerid,-1,""RED"[ERROR]:"GREY"You are not in any gang!");

    new bool:inzone = false,i;

    foreach( i : Zones)
    {

        if(IsPlayerInArea(playerid, ZInfo[i][ZminX] ,ZInfo[i][ZminY],ZInfo[i][ZmaxX],ZInfo[i][ZmaxY]))
        {
            inzone = true;

            break;
        }
    }

    if(!inzone)return SendClientMessage(playerid,-1,""RED"[ERROR] "GREY"You should be in a gang zone to use this CMD!");

    if(ZInfo[i][locked])
    {
        new str[100];

        format(str,sizeof str,""GREY"This Zone is Locked comeback in "YELLOW"%d "GREY"seconds ",ZInfo[i][timer]);

        return SendClientMessage(playerid,-1,str);
    }

    if(GInfo[playerid][Capturing]) return SendClientMessage(playerid,-1,""RED"[ERROR] "GREY"You are capturing this zone! ");

    if(ZInfo[i][U_Attack]) return SendClientMessage(playerid,-1,""RED"[ERROR] "GREY"Another gang is already set an atttack on  this zone!");

    if(!strcmp(ZInfo[i][Owner],GInfo[playerid][gangname],true)&&!isnull(ZInfo[i][Owner])) return SendClientMessage(playerid,-1,""RED"[ERROR] "GREY"Your Gang Own this Zone");

    GangZoneFlashForAll(ZInfo[i][_Zone], HexToInt("FF0000AA"));

    GInfo[playerid][Capturing] = true;

    ZInfo[i][U_Attack] = true;

    new string[150];

    format(string,sizeof string,"%s%s"ORANGE" gang has started to capture "GREEN"%s "ORANGE"zone",IntToHex(GInfo[playerid][gangcolor]),GInfo[playerid][gangname],ZInfo[i][Name]);

    SendClientMessageToAll(-1,string);

    ZInfo[i][timercap] = ZONE_CAPTURE_TIME;

    ZInfo[i][timercap_main] = SetTimerEx("CaptureZone", 1000, true, "ui", playerid, i);

    return 1;
}
```

You are still refering to `i` outside the loop. I'm not sure if this is deliberately done or not.

**Comment by Sreyas-Sreelal** [comment]
I dont see a problem over there i have put a break in the loop if the area is found and as the loop got break the iteration is stopped and `i` will get the value of that iteration part.If the area is not find the command is breaken too.

**Comment by ghost** [comment]
That's what I wanted to know... I would've probably noticed that myself had I paid more attention to what the code actually did. Thanks ;)

**Comment by Sreyas-Sreelal** [comment]
Ok i have changed the table schema. Gangleader and Gangmember fields are now tiny int.

**Comment by ghost** [comment]
I didn't bump into anything else :)

**Comment by Konstantinos-Sk** [comment]
I agree that the tables should be re-designed and add relations to it. 

_gangmember_ and _gangid_ are both stored but if a player is not in a gang (let's say, it is set to 0 by default) then is not a member.

_UserID_ is not anywhere by the way.

Set _UserName_ as UNIQUE key as well as _GangName_ columns.

Something I also told Sreyas about is storing the gang data in a global array and you can easily access the id, name etc. for a player just by storing the gang index. You can also check if the player is a member without having extra variables (if value is not equal to default).

If you're not going to use _UserID_, I'd even set _UserName_ as primary key and insert only players that are in a gang to reduce the rows (I'm not really sure if that'd be better though).

**Comment by ghost** [comment]
I'm already working on it, Konstantinos. Thank you for the tips :)
